export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';

export const LOGOUT = 'LOGOUT';

export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';

export const POST_LOADED_SUCCESS = 'POST_LOADED_SUCCESS';
export const POST_LOADED_FAIL = 'POST_LOADED_FAIL';

export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';

export const POST_DELETED_SUCCESS = 'POST_DELETED_SUCCESS';
export const POST_DELETED_FAIL = 'POST_DELETED_FAIL';

export const POST_FILTER_SUCCESS = 'POST_FILTER_SUCCESS';
export const POST_FILTER_FAIL = 'POST_FILTER_FAIL';
